apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:LiT+RYa9oeAWlXcNVjwS8MoWvTWwLcRI0MZtbRK3UHR/AvSYcGrFYWx0B4Q2VJ2wPJt9Z4VF08AfaK+kpnDWf5jHd34JL9OuOW4VcS80j3gYMvq32LnApFCglwx6wtj6zSSTe7qYu/0U3cJTNrFaPVT1qmGZVlyqytjvcdOvpeF9wtTINLjTN8sThKz5uKxilkscBv17+Yc47F+0kDgad6JniFY13gMLrgnlwtQbPTW5qqjnJfFirPG8zkhqGVRoa6TkwIoodrtgZ47XVIRfzJbEW2NStlftyErGz+xh11PotekkKVGtLhX3DNY=,iv:FsNSyldWr1cVffUUnZVkjMgN+SNbRLRCfVKUmb+VwRA=,tag:ox64MJrtbB2Hmj2ifTKIaA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOVdUeDQyYS9nY2tOVzlj
            TC9sNHRzRjZ3cWI4SmR4ZU16ekx4aU1qQUNJCmtTNzNMS09YdTR2Wnk0RnlDdmNu
            aHFyS2RtYXBLRHlyMUJNVVBxWE9RVlUKLS0tIFpUc1owUFBmVUFPMnlEMEJQWTJi
            bWhuQzg4LysvV2JoUmV4TWUxL2ZDelUKK2DR57O947PnVe2RNk70fuNlYBDisuQT
            NRpromcUyvz8ZSugfzYwBMw0V1PeKlh0m39EIPkovVZJOZl4YrwmPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T17:13:39Z"
    mac: ENC[AES256_GCM,data:p0okq0LfzJfJz64ROGMwFulGuTn75mv0zXf701dbDI9TA9spexNAPV6lQYwR4p0XXjK5Z+Avl420UGyfrVZz3QcHS6qI1KBakZsYuy6JvbGCWBIfGRO3iLTH95rDkTW3fyp72crFleW8xGugFmdqFwcVGBgz/+8qz4UdIoYnz+s=,iv:XGuwgL8ZPnjsqdjGbjiiOki4M6bKTGBSQjKBw3pFWzU=,tag:we3nSEOX4touNZCv+yfhaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
