apiVersion: v1
kind: Secret
metadata:
    name: r2-backup-creds
    namespace: n8n
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:XqOdsnhY7r14eyZhwTWG+DVSK9FrC4xCC4t0w16JSz0=,iv:W3+socln8eNBXXeRiEbxapGMPKNyoLPBbCt3GG4XcTM=,tag:ogCEVTVLPsXwW0NFEfUNRg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/sLEeSBe9EBPelFY6vm43VLwH9brs8JlrzZUSrMyG806QiKiQt4KzzRTKpJjqFSWvSvlDmWPbHcRIlfWVnUlfw==,iv:hc8iCk5LnMuQbKIR9yjPQmCdX0ANFmaGEp1s73A3Ovs=,tag:+hBB3rHuf0Mi5Lwpnmn0pA==,type:str]
    REGION: ENC[AES256_GCM,data:ZAvE7g==,iv:ritG+yPiJLnYLxIntvU/uMS02QqdfMMwfpbH1CIpAz4=,tag:J5ntpsQvtX0N4JgghlvRZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZUwvOGlvUHliN1YxVUhQ
            Z3ZpaU0vTE9ERnE1MjhEQlh3bXExbWpPTGpvClVlU3RPN0dydmFXYWIrTnNEVGF3
            WmpJb3FiQnpvVFB3d3Yxd2RlRU9RdmcKLS0tIGRQRVZmQXFKSGdDbUk2YndVYXZ2
            aktYbjVQRllKVWhGTktiQ0REMkZPa00KSlYHzYf05JAoftFZij+WiAtt21zNrTxn
            TSToxTOAaP1ial46o5C30mNp2ZpgU0RwY4yGPBK0pACGkATAQskPiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:01:45Z"
    mac: ENC[AES256_GCM,data:Hd9CjVmTT1c1NrpNHiXjFPHLgWaaY2G2q46K4RdtSb9Mkh6/biLZYnJlYRv9BrTUcahAeHi/qprAQ/GQSngHobebbW9atp1AV35HwKZrndMym86xh/Kg9XX8xTXIMlEnIqt5ozgQoI1rxiz4A1In7rjvLS2W0b2j4GLSaihRAB4=,iv:UZBe3m5ec5qvcCVgk+5XqFZvpu1xM7gMsBytR6oZObU=,tag:Bh0SS9BhKIbwHC5TtDQFRg==,type:str]
    version: 3.13.1
