apiVersion: v1
data:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:MDnfzVCDrbb+2zrejmCIDSP3uB7XZs5P+Os9fNo5kh8K0nc9Y4F9Br8WOvEaNRBPZB/TQtUY3F6Ke9fWiOJC2GY1MM/f7CyQli+eMgyXEHP5u3zAwazcxA==,iv:dUyHVqxI+CU8nyalcmpndWOOI17X79E5/fafJ9SEYPo=,tag:MxK04Di/AcPq+tMXAYhnpg==,type:str]
kind: Secret
metadata:
    name: homarr-container-env
sops:
    age:
        - recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YlN0cnlvTHFlS0ZidERL
            cnNwODhnMjRFYzZWbkpQR012c3BRSUFtTWkwCjBMSTdGRXhoTXVQRTFLZGcwanQ4
            QTMzajN1cnlGWTZiVm5rSytWOS9yUWMKLS0tIDVCcjNsZFFEQTkrVC9vU3NUWE1z
            ZWNRMlhwYWZUUTJpL25YSlpwVWNKdTgKagQBs0LTrH5zKXyKu0tkxKIiDA48fEp7
            m3KvIUoCnRoUod1ZpoK60CemoEZv8pfCNoQ2nUZESG33YHxhwnDPlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T16:16:04Z"
    mac: ENC[AES256_GCM,data:9ONDnSZSYbB8piB3QAGyIQKfDTPVJFNSeNl88OStNacY+/80h8WHxBuPiiRGCHqWVYkBXy8DiVaZD44Di/Sda51M/+NeeX9SGXxJIFL7N589JYAOjCvmPo0yFc34B5Ws9jiivwB6bdAAGpWsQ2PhUq9WR+RmNf2KBbWSltxCnGw=,iv:DtALIlx+PNjq7QTE0yTtAy91n2D6o4DBd9g4fADH11Q=,tag:B2q2YH67aeXRD2idzjAYkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
