apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
        searches:
          - flaresolverr.svc.cluster.local
          - svc.cluster.local
          - cluster.local

      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.5.0
          ports:
            - containerPort: 8191
              protocol: TCP

          envFrom:
            - configMapRef:
                name: flaresolverr-configmap
          securityContext:
            allowPrivilegeEscalation: false

      restartPolicy: Always
