apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  annotations:
    external-dns.alpha.kubernetes.io/hostname: flaresolverr.amdhql.org
  labels:
    cilium-lb-pool: pineapple-pool
spec:
  ports:
    - port: 8191
  selector:
    app: flaresolverr
  type: ClusterIP
