apiVersion: v1
kind: ConfigMap
metadata:
  name: spotdl-playlists
data:
  playlist.txt: |
    https://open.spotify.com/playlist/37i9dQZEVXbJlfUljuZExa
    https://open.spotify.com/playlist/37i9dQZF1DWWuGaVZsglfu
    https://open.spotify.com/playlist/37i9dQZF1DWYoYGBbGKurt
    https://open.spotify.com/playlist/6zCID88oNjNv9zx6puDHKj
    https://open.spotify.com/playlist/37i9dQZF1DXb1RLKxkHZ77
    https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M
    https://open.spotify.com/playlist/5MphfQSB51attP434RG2Rb
