apiVersion: v1
data:
    password: ENC[AES256_GCM,data:wUU4qgz9ETAVyRtx,iv:DI+IWTBJbpcOUST5IaF9AN7eoG5cftSsXWDKFy4ZuUQ=,tag:0fzLYDdzug9nIWY6ZbMEjQ==,type:str]
    username: ENC[AES256_GCM,data:4HHEK3L2TaAdTv2N,iv:8plL45G3XIscD7ba7O63AkxB34xFRBr36COkSeeywJI=,tag:9ovKsQJPj4ycB89LC6e/7g==,type:str]
kind: Secret
metadata:
    name: suwayomi-db-creds
sops:
    age:
        - recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMTY0SHR5NHlTekZzZ044
            UGk2QUhyVG5IenpTUEc1RGRYYk94eWtuNm13CmJqUjZCcTJqVk00MkdCSERhWFdp
            aGJIaEpLRndhTjhXMkNTQlUwNlBrZ3MKLS0tIDVGRlFZcExIcnpDeU82OHpoS0o5
            SmVxSFVDU3h2RVhLMyt3YVdXU0MzYVkKHPRGnaxcYWWT4oNE1Q0vuYIcBaIke0sv
            nK2M3FlKvAXqMWNKlQL/j2xcyQrR3nNj3/Z9QQ9KMfMQmAvfMDDP6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-15T08:19:43Z"
    mac: ENC[AES256_GCM,data:ryhs7G9Xciom1v77AMv+ffKz/OboO1Ns/cM/7FoHpqsl7rYay5lsUJe1IzeIPBiGRD99PipRwN4jYQ2F9zg8YIMKNhNWBo1/A09gjrHYCY+kF4pEicJtJH+cgn3c+adWdUFNi4TqfNrzo33PCNV44mcwWqFBiegiuas7eBjfmAM=,iv:7SSbfpzGlXftPDpkBi3c1FehDOR3YVqx9VIrXA/ggvE=,tag:0uLOhNmweRPxc2klRGTatw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
