apiVersion: v1
data:
    password: ENC[AES256_GCM,data:LbEZpm8Iyr5ORniu,iv:nv/xqFbHgue0z9SNoqEnP2ZplfXjoD6673rA5ZyyN1w=,tag:c+aHzA2RKMk3GMAhvmT5kw==,type:str]
    username: ENC[AES256_GCM,data:Ev7Kgsrb58q6+t/I,iv:pikgpZ/JadWYnJin5kX+Zo/Q5un+EvQVPUVow1Q8NTM=,tag:W7ZaRAUdwRxIY5dbXOvDNA==,type:str]
kind: Secret
metadata:
    name: suwayomi-db-creds
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNkJKVnEwMnR3WWtwbUtQ
            MEk4bTlPTitDTDhKYkJEQ3BSVTdlblhvRmpFCndCS1NJY1hZQi9DOUk3ME11Z054
            RFovdW9haDdGRGxGMURBeVVvU0NqeG8KLS0tIExacGY1WWRScnNobnU2VGVQbEZv
            a080R21KYWx4U0U2SUFIR0p2NWYwU1UKT5CF9bUNlbxpyHazO/0looXFgGPvH4cr
            h2g710MnC7qq0D9266niiYdbfNGewUhsDZRY2AbNwndQ0j5YRs5AkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T01:32:20Z"
    mac: ENC[AES256_GCM,data:mW0qzkwNlkMruOq1q5KxMVd/1nkgxFBFpCIQf06uPQKJBvrt3TS4Qpw2PQV6rpdsxNodKcgtJDou6eUI9bDHKS1oJ7RO5aPimowmNaTTM2Z7FIE69Dbe2c95WMbtAZkdrm/tSVzrQnVzHxT611xYIv0cH0TteSgNzUdKE9Y6+UY=,iv:ZYYgxArJoPzLHLoZY3EPV2ijKOzMIxLGwx+R3zib7Ag=,tag:7CaZEEisq4VnWv+AYW0T4g==,type:str]
    version: 3.13.1
