apiVersion: v1
kind: Service
metadata:
  name: suwayomi-db-lb
  namespace: suwayomi
  annotations:
    external-dns.alpha.kubernetes.io/hostname: suwayomi-db.amdhql.org
  labels:
    cilium-lb-pool: pineapple-pool
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: suwayomi-db-production-cnpg-v1
    role: primary
