apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:cDJOKDWrsWkw6JLVB2gVJNgFTSTeQ8OalLRMDKum6tuEXPIdb4amkFJloiAh2s3YYh46amEn4LeAxszLE8I7aLaYZ3IoM/nj2Hcuj5XhQIalrBLwpoLrLeRCQJJnY58UEXqS9I4QC8FTabzysxKst1iw+iHjn/vHngA6sCCp5Ge4TGdgfmMKNJfsKCSUctLYCE8SUrAm8hf7LvESO3niWBMSicS3GJxlAAE1HGu++oH0EGKR9G02//LHirZ8d52ekfe4SjnjAgjsla9QZrx4mXF5CdBaBJ8vjnjR300MDzoIsBEbEWhLG5afDcM=,iv:dSl2dG1uYutnP0l/h3Wai+pwR23+IUaiAmzFonvSvuY=,tag:g30d7sQhAkm8F+UVzcwk8g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcWp4T3BkRDFlRXhzcnlF
            NytXT1AvLzhza3RGMlJQWWk3UHUxbEh3dnlzCkcyL05zWDAwWmwyeGlYcnM0VG83
            VWtoMUp4MG81dExWSzRIdkptc2d4RVUKLS0tIElkczI0WGZNa2ZSZXpsM1ZXNm1C
            TmswdjIwWXU0UmtZVXJaZTBqcTJxS2MKmnxzzPXUWZHEMMF7YUjug8K3TGeBOmLS
            Kfy1nf1L+fpy2nKS5A6xLVNnJZPkUFAr3cnmr4iabVP1ntWvn9m74A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T05:50:00Z"
    mac: ENC[AES256_GCM,data:FvrPFX9uDVebheBTNSUTaUYWIcJOQNybhfjpwsGmILC00m/I+akQTkcAMUhHibIYoAgRnEjYVOPVt3NFq9QJLh4jfGxexXCoWVS9ktfp5BYPxGfVmLOHrNfuQMEXDQRmSkKIVy08HdD2PKorgQSzv55+hjSFtc3XDgodVgLQjJ4=,iv:pzcvhJCvDtfbiaKIBkiUppQribSPw5GtJut/ZdLObV0=,tag:m5pTf/cu2ty4S1MR0dEIGg==,type:str]
    version: 3.13.1
