apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db-production-cnpg-v1
  labels:
    cilium-lb-pool: pineapple-pool
  annotations:
    external-dns.alpha.kubernetes.io/hostname: commafeed-db.amdhql.org
spec:
  description: Postgres cluster for the commafeed application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 3

  monitoring:
    enablePodMonitor: true

  inheritedMetadata:
    labels:
      app: commafeed-database
      policy-type: "database"

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: commafeed
      owner: commafeed
      secret:
        name: commafeed-db-creds

  # handy: resources can be used to trigger a redeploy
  resources:
    requests:
      memory: 600Mi
