apiVersion: v1
kind: Service
metadata:
  name: commafeed-db-lb
  namespace: commafeed
  annotations:
    external-dns.alpha.kubernetes.io/hostname: commafeed-db.amdhql.org
  labels:
    cilium-lb-pool: pineapple-pool
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: commafeed-db
    role: primary
