apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "0.14.5" # or latest
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
