apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/metallb/metallb.git
  ref:
    branch: main
