apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:A5Q164O1MpOjO0tW7OUqZgsFaRlrrwKoFPbQ6Ivw9Fi09HsZJ2m7lGUL4AgS5muV5OWr91jy+eY9lfdwNwh29sSgsAI2gb2TsOuUPPTAf/DxmX9WW6nTlw2BtIWEEWzqmMj3RFhMuHee7zMLVroNf9F0xQL+bCvi4jk48pED5AM9gL+DObYXpJu6RXYDqQiU6kltGUPoPQdS80qrljbebp83wFZg2Tl++CkQGbfnkW1tfRKnZSJ7jwF1tGHXEnnp3P9fX4kM5SVBpyXkQq76uLseLVOSc3ShvxE2kKpEJrm/9QoaFGPZdZZisq0=,iv:wCzfD5xYWgwx5kSSMWvdJk3dtgYYyxOoPHG1nVEsq5g=,tag:UmLkQ1+EK9Om0VYmqGdtxA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-prowlarr
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbkJLMjViUTZYcWdJZFFR
            S3FSQnlOejlMR0hwNENYbEJiNTE1d1hPQkJZCng4Y3FzTEpiSkVKSC8zQkwyYUR3
            a2pFQTFyZjYvUk1hNTFBN2NKZDVwNTAKLS0tIFlxZ21xVmZ4NGU0NktQMmpQZENo
            VXlPbkJMMEdSVWRKanpGQXZYTlNhUXcKKwQvt6g0TuoJDyLR0zA2oao7DYesHSc2
            pZL+nqUg7nkGYOaUuCUMwltkQIsFemcYpdHaYqDbYfL6EocuzsWazg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T16:00:42Z"
    mac: ENC[AES256_GCM,data:KfQjci+J4bMMWiaNPl3Wu5uWQaAgGr7i4H/xr9VtrmFJQqzGk84+LFR8Iz+dSVj9cbDnZcTmXb1KGKaepuMMSy6HleXr+lSKchuQ/fdr0kSSv7BQ3wqaxfz1IiLw5snL9cjawrRvrUYsyQkJreO+ZcXCGCQQm4rWxoKJPNwVo4U=,iv:YZi0PRp4MkSAMUvYBVhPbLX7FNKgMWYlL9V/XHvls/4=,tag:r/zeNfQxNImk0nnMwRJwSA==,type:str]
    version: 3.13.1
