apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-container-env
stringData:
    SPARKY_FITNESS_DB_USER: ENC[AES256_GCM,data:dDNwClHSotfdUWzb,iv:Peha5mvkoVfyFn+hLPRdaaleX9BlbPGnSTGWRdzsgfw=,tag:dN6zYmwZeKmDrqy0+T7DlQ==,type:str]
    SPARKY_FITNESS_DB_PASSWORD: ENC[AES256_GCM,data:n3cCpI6j4OxMl2a1ULtvyPKw1vnEaJS5ZQ/Jj17iFyw=,iv:82eHJ5vZyIaH6Xd/aLQj2bLSRMP98MoJG8uyBoCx+FU=,tag:Qy642yEmSHMTZsTuc9r3EA==,type:str]
    SPARKY_FITNESS_APP_DB_USER: ENC[AES256_GCM,data:xWCy2eP1Bl8aGA==,iv:pGi3iu9HcC0fNP4Av3H8efUXYyktrMuO61cmPvkvcjo=,tag:MLqcPX9chaSzX5tgQt/nYg==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:fvtLQiM/lBk/j2ACMSDU3os2hcUIbTWEkTGk95N0o2A=,iv:HQKp4sw7Yqs4P+5k+nOCxY2znYulmsTmSIg/UfZEvbo=,tag:I1o3TroiW3K7laJkWZz73w==,type:str]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:FDs/yO+PKo4I+TaA6qDsw1Oo5954miS54OL6enqmbU+oM1g9iq2La8YhRi/mmd31OXYemdANRAWbWOrF2WvKIQ==,iv:es34RD4fPQdfZd77j8GfYMq79T5Q178Wfju9IYs3FDM=,tag:9cXgPQ4TWFBjYoNlNiBegw==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:Ize/JxgU7Aq0KGoX1jxRGjK2RsVrmhZA6l7ReyPpS4PViEUeKVfE9lwiVCw=,iv:IeLN08p50p87hKILISRhbFUlKFNJ1SV1iLlZ8lI7rzo=,tag:Gqq5envpxUp0EWv1acVbBw==,type:str]
    SPARKY_FITNESS_ADMIN_EMAIL: ENC[AES256_GCM,data:u9e7mvs8fxVZZiQKbmeWAXdVdg==,iv:c7SxZk4HJeHl7Ro7LcYij51GbXLR1eOV+NtMX+Nz040=,tag:K81guEAmkTxyoJXsd/buhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBianQrU21LSURvbkxLN3B6
            bjJTSkt0OUpXYkk2Z01DeDN5OVBlY2JuUlhvCnlMcm5LU25KMytkdFM5TnhwbE5t
            VzJVNHJnS0Fwcm1yTWV3R1dEYk5HWDgKLS0tIE1lZFdORU16bmNWcVI1SlFuL1Ex
            Tkt1ZUJlaE8xN0ZjSEQ5K01HcFpOc2MK5nOAE+/1d9wIVnYk1LSb5q18kyhlc2rg
            VtOw4j5tfW3ylxit6UXUmlY0O4U1kIf/YmDxwzQ3LtAKmJ1v9AY8vQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T08:38:43Z"
    mac: ENC[AES256_GCM,data:22+GgYgw4sfk3VBVrcPjaZJ4T0LnUY9AZ7SPk/Zf4TN6k+IY8b02a0UPRzQWTC99xyqE0vnrDmnFt9Ul68+UgLuAQU92lxKA1EYfJdu0iLfhUVvA8Oz/VPXdqQgakNkvs7nH6RYHmvDk+YJebBVsPnZLLd4gC08DL21ZmtF9rzI=,iv:u2xGLSRtAGnFGHv88vqjyy6nx+yfwQPNHOMKWwNBA9s=,tag:dbchaeP5mv0RaNhiK5QGGg==,type:str]
    version: 3.13.1
