apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness
spec:
  ports:
    - port: 80
  selector:
    app: sparkyfitness-frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-server
spec:
  ports:
    - port: 3010
  selector:
    app: sparkyfitness-server
  type: ClusterIP
