apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:rE0+rvteIZtUSJwmrU7THVV++rfD/gNOuKS4cIc1ft0tpX5A5i+OkkeJcaCn+Y2zZ8hJzjx6NdWyo65pv9n6UCyaIR3l3x/Qne5+Ogdddp6vI+2VaS4Gex8hFWBo/zywfX1BukwWh0zn7XPZNbz70l4b/INM4i4hU6x1Y8v/Ourxw63A4984ooFyWIf3d764xgXF2cGcPjc7aUnUVpqW+RJFfkngeRxc7td+TZX+G2d+3qPhcTNBKjPvafVUAwcCyT12nWpMPRG+V8iqp5KE6qSleeN6arzzbHWxMjY6EoVqNDUSMu+vHCITD08=,iv:kwTcu2qdy4KDr7PRJCJXjulH/5/zmlhl1hkYAo4g97s=,tag:kjb/aNpMn0TqK8fh9ll+ag==,type:str]
kind: Secret
metadata:
    name: tunnel-credentals
sops:
    age:
        - recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VHNKeC9ZUHlWTldhRUll
            TkNBWHl6aXNlNUI1V2NvVlZva25IWmI0dkFFCmRFUXRyU3JVVzZ2TUtrSkFWKzN0
            S3VXOTc5emZhTGN1KzhTRE1QdjFvMjQKLS0tIGxTbXdaSXR5OVlVT212eXZrSFUr
            ZDhkdVVrMndmQ1o3dy80WkZpNzJ6RFEKc5XvsHUXVp/3W/hAisS1q62PUUtcEPEu
            fNwVubdDQ5PagO1wmwhARaeiDVK6u4Xp2lPWT1vjU0ib0F53leYiXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T16:24:27Z"
    mac: ENC[AES256_GCM,data:IzJzR8TiW2KEc6Mv94o1RdwYIpSS0BnZTLw1Ue8TeVYJIdRbgUCkXgUEoidn5i+pPSRvIMtWQo+g50B7WNqWNwZEl1N+WlAlwIasnCMt6i8Mz0HoAJDfcMcZSMAsXz/+VT3q4TVoSPHfG9w9IBKNEN2AGaraFTOfU+5+DW/7E9U=,iv:b5i5QZ3xdjfT5yCFF0OI1rqwndvFzKK7hb0krI0X9mA=,tag:o124tyByX0G2Jl9PBJoqxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
