apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:HM0tZwpu4OmWgbDdkOJay3qx5iirEsNBCty1AMHNpWtnsGBhMlnPaqAkvz/LCkwMx/1OOubyis3N9MTPL8vXaGTuM01VQse5Q7qZceUQ0j+oYnJx5StiqI/HJxE96pDVw37StftCPML51dLBcC8fzHAz2UVbXtyUlvfnDz7kvFeYe2a1RjK+6fYKeT50kGSs/hUAmKC1Yg/iRqRJagg9Ep/NTUhhB5QcKrBlEKjSuw9wa73TSI4CD7bfs1h0JBba2i+iQz/T555Nlut15VCJMTeP8JO/y1x49mH+DpRYpW0lFBUSHkx6MzDuoSY=,iv:tM7skXQipuFl3pknbS1QnmyIp7CT7ZaMIwSNjM7KR0w=,tag:CFo0dd6o2XGw7yabmTuFBQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-qbittorrent
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVk5LRUZGY3dvUXA4ckFY
            Nm1jdVlFUm5CRWcvU3M3MUxEK2txSml2akhrCnpUazlRNGcwOXY2TUhzOFhPRzh6
            NFJJd1BuMEtwMmNxbDMvSHBnQWp2UWcKLS0tIEtnMlpCSUovNGNkaG15dURoendM
            TFFtRUtjeklkNGoxcjNPZFhvZUJDWXMK9PdFLuXUadjfXBsgcnkdd9oqNNPQGvg9
            q1wzqzQqw4QSNwm9ZHkiaH/hVTbt3CGu3HAh/FduotPKgB8JtFuO1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T15:02:11Z"
    mac: ENC[AES256_GCM,data:W9fUmSIu8Mh6JxFhZpV8HEfqQC7PKC5+VCFkG1g2C6GnVCPHSRuWN7DNptJILkX+2v10PsU3WVN7AKRPDiIuL5TTT0auJ/Kc7by4C1k4MFpdhSoAnlS7qVMo0IGvR+ef+bKFxL1oIO/cJHz4lfEdusagkYeqigsBVZhEnvALkS4=,iv:KG+uRZOGx+YxRInb0KLRAvQ72weVQDCzMag8DT/xJSM=,tag:p9qdRgJAKzyZ8QnpX9LSgw==,type:str]
    version: 3.13.1
