apiVersion: v1
kind: Secret
metadata:
    name: gluetun-vpn-credentials
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:hzTsJBP8U6DmibYS5i/iRw==,iv:XFnTjueeAljU0TaDhrGXeRFQy0bGyd6BUFJ7lYFS49E=,tag:2UgJfmmGuUucPW+Ix1YH0w==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:IWXI8Jeih00MwXBigCVL8G8aJ54DEt0myvhR8RalGSfxurbD,iv:JFPIY4bcClHrTDMknnZsC6E0iX9wit6XArCytuPAFVE=,tag:VIohAQJd6cIKrSAUzUcJsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTXFmZEJLUmFxaUJ0NklF
            eFJ3aDI4OG1CbkNQalQ3V3BoN1g0c1kxVXlvCm15QWoyOWRCRnlRWmxPbkxmUll5
            K3hXR0ZHdnEzYnZIdm5nWnVIcFpaV0UKLS0tIFlKb1ZvTENzNFU5SUU4QkROQmZq
            R1dpUHFTRW9DR3NueWQxeDk0M2p6QkEK+ymiFj1DLaabXhhbshDOW1qrYiHR1CLh
            yZV97db5OYKWfYJze7SOjVWEcGFARqZ/k12Kzoy4V+gVDMfqxVYIlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T23:49:04Z"
    mac: ENC[AES256_GCM,data:XKr0nSI7wV9XJqDbzdP7+BV8aadtE2ZVfNsPtkUWvkIKmRc56LlywuD05ScWN8Ya5EZolrETWNN5VMxD9MD8BDPjTyZMuT8H0HcjppHdoPJwnxPc9HYYexRe2yQWnXn1w1WtKkVfj8cVOADkm97ubaJeB70bl+gk4CJe5/W6D1s=,iv:bKEBuULDFhOGqCQFEO3RN9X2f0X4aewtOlVdT1sxz/w=,tag:IbFmid2VEaWSRhsX04s7kA==,type:str]
    version: 3.13.1
