apiVersion: v1
kind: Secret
metadata:
    name: gluetun-vpn-credentials
stringData:
    OPENVPN_USER: ENC[AES256_GCM,data:8GH7v9ibtx6dg9s9r02eiQ==,iv:jbed4ZAlS5XJSXPwcsZ4SOUKENz7Hx1P1YUBDjxX9OU=,tag:+t8KsVuSoqsxagQlFrf4cA==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:8ZoZ1+GaYdNk7kIBB/F+z8UpnSTVMp7k0DAUYM79Gaw=,iv:7t5iAkBOICCm1fAtgP3nI9zIRULrss8RZoZj18hqp/8=,tag:+6Pn0fuU2C7MTRnWkJCegQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbk1SK3gweE9MSzRDUURh
            dFZtcm8raVVwMFlDS1RlNU1oU3psU09XWjI4CmdyOTlqMnlQcVBsYjViN2NMWTJW
            YW1ncENqeit6RldwbHowdlVJSmNickkKLS0tIGlVTVRRZ1pjc0ZMS3VsQ1IxMjBU
            WXE3OWFoKzI0REx4aU9XTS91Mi9xcE0KfDlZMriv/XY/rDMFujkQyvkZNWS/oD7h
            JBwi6kRywl4Wr2H68k9tiSA0eHEaekqy/F9hWOrvtMeOnV7BVq6hmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T23:54:44Z"
    mac: ENC[AES256_GCM,data:DwffJQGHkvMyR9DI6HJX0Coz8pjd8XqR7Kgnj3sH8rpK9W8pCj3Pk9z1COdfWBwsW1d8dFzJrtV3CbFp7sOHqUWiyWTjkApIfvD9nENhIUz3a9lGDqGmsqwKRoigZs8J0yJnI/AfzkxIRG08vYgdtAWTpBCIlXDb+v+ystgJpoo=,iv:oG8BaypT1x9WojaakavJTOF9zAotUGJ7N4wUh+y2+NU=,tag:O2OxJrCM5PeyRKgb+doVaw==,type:str]
    version: 3.13.1
