apiVersion: v1
kind: Secret
metadata:
    name: gluetun-vpn-credentials
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:HaBYUQOBKLKOy1YaUzv5gCpyse9jS8WfJnF7t2yDW252tQDYMUp3cKSWTH4=,iv:b+KeMzpNr/z6dcsmAFA1vzneaESsSusnAQBpRCmUnzY=,tag:AROkBkSdVKlg/xDGmoOjnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYTBoT28xcWg3SjBpNXhD
            S1c3eHkwSHp5MVRLRWFGU2toN0tDTkFNT0FRCmllOVFsL040NG05NWJBTEMvSXlo
            YVhvN0c3amVDcDVtdnRnMERrSmxpd0kKLS0tIDMxZGI1QlBiaFgyWGFxdkRoVVJm
            MmVWbXBlejFCbGV4bWdXNTVCK1pmdDgK96zEZRTMaUUhEgQAZiBXcJXthXifBjul
            Pa6N9U5BPSmpCUtvNXm6yeRs/1BUSrBJSTEGM26g7l06Uq2xjHXobQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T16:21:04Z"
    mac: ENC[AES256_GCM,data:H/37qkI8my1Mtne56miALD3x1roYQIs0EoQiu0J8xtMvbAZEsKKPE+qWvgUokR/5qxskhPQV+MBEEEmzqPOhy/PkBzvmIsi8Dwo+gRGx3YG4jg2RRGSQKK2pBZ8g/bPDJpcqTOTnox6pu5HbNQ/QlkVzv66IRy3V2rnqvgp63uA=,iv:FQ1HpNV9gaybVy2I15xufGh5VzxeFGy9vXvTvdPvt4g=,tag:BqEwEUoGeu2VsfLBp19y7A==,type:str]
    version: 3.13.1
