apiVersion: kustomize.config.k8s.io/v2
kind: Kustomization
namespace: external-dns
resources:
  - namespace.yaml
  - secrets.yaml
  - release.yaml
  - repository.yaml

configMapGenerator:
  - name: external-dns-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
