apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:h87WHvv6kF3jCiDu18wI8CUk7xpjFHEhmAwQCzjHgKASuaILAEZngWfMm45goZNYsWpL3vk+SJilrUj+pfzdvEhrGjC7FIPISJZtFgdD+tzIPLHLQhobAMh9ncY0hKv+6aNfz/qRMfo1R6hO6poeTZNHNvIRrqx4Idiw7SuGE+Yazpk29VxIaNvWx6qbZF/qwyHjDpburdzI+1gRYHkZmQt42RYMeL3L43CKeYpWsHtuKK05PG2gwSryQQq/K90G/Yh+EjZVCKUX4Vmld6LFRqltd549ySBcQmRiPyuvZKvH0M2hfpeOY4RwBqc=,iv:Kw8GgUm0+2pwItdFMHSDSvE/VTEm2g8oxFb9Pl8KVNk=,tag:gpIRKlUSRKFkcq5b4+cg0g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-sonarr
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR2tpVVJ4SWk3czJHVU5i
            K0FNUzdLQU1Janc2NGZ3RlU4SU52UU9VRFVrCkRYMjZES0k1VG0yTnVsMUh3YzlH
            dHJyT2s2ZmZqZk5KdHlxT0dNclYvek0KLS0tIG9hN0FPeDVIdGlQazRaNjYwN1ZC
            U1ZXMnllU2ducjAzckZxMW5TMXlTZ2cKmAXDT+ZOE8V/+A/5Dlkl3FQRaext7r3X
            wjVaKvspf5kPa6EvtPzbFHZyUXP/lmYwPtWa9qwMVY+9ddKhsACibw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T16:07:51Z"
    mac: ENC[AES256_GCM,data:qmjyueoX+cnavupDnYGSQRPMWA0cPZbtIh1BounAPTKXs+Hgs+hYim8ADzk9R4icHn0bs50NX9+IetGYtQgtPHBHVwbMWqeNDQUgoNE9ljzN4nZgwBbUMK4TTFUXQGO8cOG941Jh2wovzB6ZqVrApLfoNbm2rpz1Cy4Gqw0/UUE=,iv:HQDl+Ui3IVo058LYFCB6t0V+j53EDXXqdgfGvOfPuDU=,tag:+jYa0wbIVYOpXOHU0URJeg==,type:str]
    version: 3.13.1
