apiVersion: v1
kind: Secret
metadata:
    name: r2-backup-creds
    namespace: sparkyfitness
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:FaKlo4RTeweaPrgVO3YuPXxbbJLxAMqf9Ciu/VtRk1E=,iv:Yc6Hop0w6p1/7Oxx5oiJd2dbPC/M526Wypz3tEMM4X0=,tag:QyRn95wJO0wzBdnHJSHsXA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x8tCS1wZSLiSYZXYC6nGqcgjSkW7aKD/ZWa4+5dl1YePuXABnKLegVL/XxNYP7pjTcmixVarO1MkXwSo3JA37A==,iv:WuKTMee0G5dniJVwGNZNb6ag9XCMW/Ke+LRWi6O+WyY=,tag:SjKHqbF0XvMkvp4bhHw/YA==,type:str]
    REGION: ENC[AES256_GCM,data:1vIHAQ==,iv:YZ7Os+X1eEjGvUmyu4x1rGlUvb1pMp0qZBa5I9tQZ2E=,tag:GGVAYQ/AQD7ApYIYrclWKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzV2crRUw2L1R6NU9ldGRN
            aUh4N29SN0w5a2pYejlFRlE5eGJrQlZ5aTA4ClZ2a1dnQi9qd3dVeXR6cE5kVGp0
            RHRVdXFkUGx0dEtaSUN3akQxVXc4NE0KLS0tIGRPayt2MW11S1JFUDQxZ01NVHRm
            RE9OdXpDbVRrY3k4TndOR1hQSmZQQnMKiRkoV9bYw0fQcjPef7QbrpD1rte5UaGd
            nx7vA1CXUlzSqH39imMA7NPXvE9eEMAXn2E1laftPTe43WCLXDIgsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:01:45Z"
    mac: ENC[AES256_GCM,data:1xoZNcwCaq9xgwAj4VVQqNVD5cxVQoHeC+rt9769Bz7KaQKvyqaY+eYYgw9L4POpm2LXk144SzTD+o/Rc57RkBFd7aV38Ztr2HdfpkKL7ae43AEVHhZ9a/oS2fxST0RKhMbmIdK8Vz8/zWNYaq9K/CaYFEuqbBIdcr2QterzB8w=,iv:0Q+7+T5H6JWvr4vn8t1YEqHN7g73706ibNudVf7iGYY=,tag:FKoxwcDr9t99Cyl8SoMy9A==,type:str]
    version: 3.13.1
