apiVersion: v1
kind: Secret
metadata:
    name: sparkyfitness-db-creds
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:17fs/zKPs3Kk212A,iv:L8yqiJBaHaiZDMIY/jP+lkwjWo+l2iixM6BxfLpm0Rs=,tag:35WxNXCqJOqaKPd4LYOJ8w==,type:str]
    password: ENC[AES256_GCM,data:WgYkOK6zTYTVxlcOyVSjM4LALEqbgdVDwq/uLvcV++8=,iv:9qrV+6jcateTxqvAi4o9kB7KvHhvei6yvPCf4dFiGQY=,tag:FVhGK+laJCIBvXmGEd+A5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMUQ2cHpjT0ZTRzhXZWNY
            OURTQUhBc2VEZUZQUURLWDhuZ0tvZUJ0bG1BCkt6SWRoRGw3Z1l0REdEbzloZWVG
            ZE00UDJvWTE1d1F6eFp0U2FZOGtWaDAKLS0tIDMwMW9sRHpPdE5vK3daTnB2d2Iy
            eVJVYjBQZUZxRTFoQU90a0VOT1hhWGcKffapFhSrL1NiSK+e76MPPzOAXHUsaWeG
            nnnY2lhMinBhqH+eJJfEGpqRXz9kHg3Z8GWxnklerYkSfyd8tYN3Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T08:38:43Z"
    mac: ENC[AES256_GCM,data:xVH89QuzHtwhQEGweVpsEMY76Sap6Yn2Zn1YXDT446oiB954O3VrltQIi6kQv69z9hqDnLcN8pQFHLaSQPINb/BrX249/rWp1kzBECLIQ5oF2BHS0Wm/mavoD20CgXsTkP6s9Z0bEMEipjgiN2JJzVAQ/7IMbHXjaZZLLyTkS1g=,iv:Tsd0xSbZu+xsB2G8uKyI3JiVwY4mX0MkPqenvtfHyf4=,tag:DHqPCOpQ12u+WbWxuxteiw==,type:str]
    version: 3.13.1
