apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: pineapple-policy
  namespace: kube-system
spec:
  interfaces:
    - eno1
    - enp1s0
  serviceSelector:
    matchLabels:
      cilium-lb-pool: pineapple-pool

  loadBalancerIPs: true
