apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:gwVeU25CXRIWEuPjl4HB/FqqD41kysJvvqdjuuYcwvX4fv6v0csoZ/2lvauZIxrLLUCI0P82s5A6Altm8Cuk6Rfchh9/jIQVstFIBFRzwFkHyaauUAx8SQ8Zy/ylTZoTuiAz1PTP4r3TBNfxxTbDSpSzK6TD2kP9bKPOaaCSbreXN7uJ1pk3gOhaN206fVoJcuWNbabqm3QC6IvtFxgqWg0bOqXmtoslJW4V+B9UcXZ4A3Wr0allCIA+Hobdk7n6wj051ce19m7O/rlca4Cz5X4Be2RvKPwr01ED8/D9vrY4OpudGhpVdEGc8O0=,iv:fPV54kevLniefzhEfVaRcwgRma83f3esfsIAI/EKrgM=,tag:TZqSPwhJSF+kkuQi7xWRjA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-lubelogger
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc0lOd3pFSXBzc0JIa1M3
            dG54SWVobkZoUEN6OWsyZlNqK2Zlc2tweUJZClk4QkVnenA3QU5vdHNvaVVSM3Ay
            dDR0MlplNHMxKzMycCtERmw1eWNHU2cKLS0tIDZyWm1OMTFKOWEzNHQzdXlScGpw
            TDZqVXJ1cnF6ZzdWSm5IdzBmT3NwMm8KDmjetZ68y21agdd2yLhhXyt8cqeafHz5
            5jskhOL7UYRO9htkGMAWLhn0Muw64O7u+mPXEwwZQ7iNrfbU56yvfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T14:22:50Z"
    mac: ENC[AES256_GCM,data:N9fWXMdJuLyGCQ240Jw6f0kDRKzxR+3orxAsAq10+4hmZrMV+jUo93aTaiuvNzCn0em9Up4sXnP7CVuOcPRMpJVxG2I8nUUL31CUnK5GpWYyfLdoHfNViWyCEgrfHSyMle29qJhI9eWoOwg2QANhCidnLffPmzRKk/Z6v1xwOu4=,iv:kGIERhqUs+N50R9JIMLHuDQTtRJZ5f5Yej4vIUSVhFM=,tag:+dicYEWZNwbZTDSMdtV7Vg==,type:str]
    version: 3.13.1
