apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - release.yaml
  - repository.yaml

configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=vvalues.yaml

configurations:
  - kustomizeconfig.yaml
