apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      version: 1.16.0 # or latest
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
