apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:xdBgLyYh+chO6dih9ch/Js5m9jYfxloodG1Agh0v9iLI1GEy/dwH6l24LTlsFUyAZfrAxdQdzkj9uOuiGfuSok3yc9GDjH1+r6nuTdRS7+a59c/pr/FssnP8nl3pVjiVv8KgKerhcb56VqcYtXao8nzCADNnXyW8JJJf65/J2rlhuMa+R9SlUzO9ec1ZJ3owKuzCvwLwiUymkuboSZu8Xve452C2UMs8QBRZHTJPnZ5YmP7vNO1d3HYjNRbO7sfR15nceRuTrJE6vjfnkluTgCqt/G3BiIhJSKVI8Z7StH2PAm23O9XRbYi8Tm0=,iv:4CSPkQQyTu88HAaipm3hZrHR+NWePEYOIXDp6zThcYo=,tag:0W+bGHw2en85vgf64KsR5Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRzloV1ZtRzR2cVRSdTds
            ejA0bHNNUHRsZjlhVDkzOStXcHgwUHcwWGpvCkxSTk1CVDVSWVVIRlAvVE1wRFJ6
            eDFkNXhPSXlOMWlVd2xkaERHOXFiVk0KLS0tIG9WYnRHMGtPWGk3N3ppMXRQV3Vi
            SnJUQi92NEJzZnlYS1hGbnpnMncrdE0K6FdQo4clYRS6wO2mw8lw96FC3hgm0suH
            yDNyrYRFLzmDgP6s/XVDw4xMLyV/HX26QHqhmMkTXEI4e6PcGi87lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T17:29:39Z"
    mac: ENC[AES256_GCM,data:nw6n5Iv3c8MzKBlGUwYIROnIOyf0cJ3163ulGWiFoUiDhnI/eGNMCDZgSLCD5dtWvHd3pas9GEbVCfoy6r+y3QFUMk7UIkQKbwT7HZkOKcaT8w50b5IbJP/8nkGQpnW9zrY3QVTHf1CRUY1uqLGkbTq//O9An8qVyXgZ0ICMGX8=,iv:DwTq7NLgoLEJTYMV0VrWb8vWoSC8WAGemXxW30nTvBY=,tag:5/bLpLBnMzKocGw5GBDV/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
