apiVersion: apps/v1
kind: Deployment
metadata:
  name: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stremio
  template:
    metadata:
      labels:
        app: stremio
    spec:
      containers:
        - name: stremio
          image: tsaridas/stremio-docker:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SERVER_URL
              value: "https://stremio.amdhql.org"

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: stremio-data
              mountPath: /root/.stremio-server

      restartPolicy: Always

      volumes:
        - name: stremio-data
          persistentVolumeClaim:
            claimName: stremio-data-pvc
