apiVersion: v1
data:
    PASSWORD: ENC[AES256_GCM,data:Nw7qfgH4Di9NOFTVY5d9W8/Za54=,iv:P4lLkwxzhfcqje9VLZ6MhWzcyG3yic70p5Brv1mAiks=,tag:izkjScUJKHxSulEKEkNENg==,type:str]
    USERNAME: ENC[AES256_GCM,data:mZMGiNUFBXmYgIt5,iv:/zP6Qkd9gPIP/YmmfUmt4bCD2ylTU6fsnAJhFOehxGo=,tag:+gXCW7wN9Hg7fph5BCJC8Q==,type:str]
kind: Secret
metadata:
    name: stremio-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTjZhNjhpUzh1YitTTXVu
            dldxaEpWazUyL25oNmkrdGxHU0NiM2FZVzE4CnVwTk5oaUFjMTRGazdPUDA0bDR2
            UDUxMzA3Q29RRE5nWkJpYzNyNkJzYWsKLS0tIEQ4eXRKc2NscyswK3JzN01qd0Zw
            dlBYQTBqMGRSK0szWHppZDREWlg5RWsKShFXdbrRqWBs1qbysfPEbKICAI1H+GiZ
            Q1IrqkPXCluPxQnoAkNJxvOiygQKFbmBk9j2Gv7kKaQFlhADdjMIHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T14:24:35Z"
    mac: ENC[AES256_GCM,data:riM9hebb+5+cSrbXkAeWE+vJtGqbgXRsy7gaRr+HARxNW3VA/5VVP0T8OB3/AFLkqowSJc0slEqG8yg+Xb6fSOZ7yIDcsjM0XeeASg9/Uh3XPn1T9F9bPccHf6cakAoCFUr/CZkMINOx7FdyZI3IlRJNwUGcBpfD8zztUeTMaAc=,iv:oX0PODncTRp/eKZwEDUTYwQGE1ZzaOsuVgYYfm7CY1Y=,tag:/OaVuia42GmT5hb77vAWPQ==,type:str]
    version: 3.13.1
