apiVersion: v1
kind: Secret
metadata:
    name: r2-backup-creds
    namespace: firefly-iii
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:1JSb/CnKQYBYk2u3E0j6D+H9QqIwu+2H2e0m/zXR584=,iv:ybZwfzoi08pDN7J2AnARvb0cy7qUApR1LjM4gbK2vqQ=,tag:b3GbmWn/c+PgITadjl929A==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8rZqcZQLh32uMKKSqKdxxQsa+r0Ceb8wSM9fvGleZOvTNuocvFJcZ2WRbsGPIWdvpf/Kk1YtLPZ98pjf9Q7aJg==,iv:bhkDRyUUSdiyGOx8xtDviI56K0gtC+Zf6PGsYl9br+M=,tag:1E4MjXLena6b7LSswzvBfg==,type:str]
    REGION: ENC[AES256_GCM,data:+p6gZw==,iv:3xijCAFQSlXnDcdx/FUS+2B+H3WMk4knKgEQoT9fF9w=,tag:4sj4KsUkPLp9sBnoQ5Pxtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldCtqTmFWZnU4YUdtQmdI
            Y3ZmL1I0ek81VStNOUdmTFN3bEJwNjg3V2tVCmxjMGRsMk9UaERIN0pJS0FWNy9W
            aDFxWlVMQTNubVM2Sy85a0kydjhoTDAKLS0tIFBIbzlzUE1ibkZ6UTVrd2RBRkt3
            SFhQZmVCUTJsNmVHeHU2N0Z5bnRwb0UK0HvtdsOiADfXj/nqdXITBIBFxjptJexr
            t+QvBBNQyFDldY6ynpe7UlBMEEH/Wljj3AZ6VOsC2AM/WHG1/c/c3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:01:45Z"
    mac: ENC[AES256_GCM,data:XW5jFXQenTkyGiZ0vpeWRasudShzA7e3270oCGUeCZunSZwxQaOHI0Wx0qCvEwZAJ1Cvkyt0BIfH2OsCESUDyGOD+sTtT4pXGBsLMUeZmgff0vB/dqm5lF3jQUspmivwI6UKCWNwIEo8OZwrQralvCkyipO7vQD5QoFxPSjjmhM=,iv:qD0IeqnbM10ZdD1dgWVaScn70tTBmpIx/CoNi27q+IE=,tag:QTkDfdI0c/u5EIeruesIcQ==,type:str]
    version: 3.13.1
