apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:NlbR2yTstH1P1SoCbFjSqY2YaoV4yERymMyPUeGY7qnIzj/yId2FTFfZdjPvrxGBzCAwlM4UVNwXbkVe3TVW5I9AEBoxqWPPYssHWvfbtOn/mwLS7d2XNiA7FGO/B8e+btnMFKN8Un1XgcSiOE80vCt4JEwCGm1vfWvHxli8m2c02Fk+azAKGuDDAmoiLH0yvjvCPVnuTs6cjdgVXa6hzjHOEINFWklcH3jlgfpyXTPlX7Ox7PMwTb5JBMuJZmaa07U7GRCa2q2DMt7WKZM5FuqYFbAHmlTTrrNmoo2n8NpgxT4qKWO/Zg2Ybqs=,iv:pAKz+LllVHh4gmqq/SpF2unowlxWc+nomz4HWoLPviI=,tag:2X2H92hAXiI9RCliZDFVBA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdW1vdFdBdGpBTnprbFk3
            K0t6bmpXeHo1c0QxMjYwOXBwT2RmM0hESXlBCmkyVkpMVHltczZaUVhpWitIU201
            dTFqZHVucmJSWDdQOCszQVNoZFlaQzgKLS0tIGF3SXJHaHpLSzlGZmc0dElOUFR1
            TDZRb3dWd1c1dFpTSEl6Y1IzSzlwWlkKMYfFcstckslJ/NRVw9Rp6/8MXEujaIU0
            JC+/MUfmCbGhEtlN2qB2oDuoWm0oO0+1akuyg9ABsYySSgXCxJZslQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-21T16:44:29Z"
    mac: ENC[AES256_GCM,data:nmhyOvuDi/QzkfUqqLwcAMB9C89FWqPb8pBjnpJXhhouJVz2L6W+yPh3oPy41NmYSieoOxrfF4QSZyHBMOQChA+GADlKjqSrDhbffT+Ga4XogQIxJYgi6an8wDZxoctvZbddh5V//RypI0iuIUVC0KqRK/kZpBB1vgTFTSEB/Fg=,iv:sPJhsrfP7F9KtwGYeJIpXASVtCe0EaE9uYnI69HkhIg=,tag:S16CRoGDzetD5cCF5TczTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
