apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
data:
    credentials.json: ENC[AES256_GCM,data:l7xRrbR4Aygt6u8N+ayP1RolIk/bGYAjf04+1lOyQX5lyCW1t+0NHijgDgpU3+CRPpqI+ra7GmTnKOSU7DOD7p7Rw+10tiw77wTVBKY8/LqBfcaZCBe4G6j3zDnuY3xw2/wm62cAw3KZ9kLkcbIMXvnoNQvu4FoTowwxOHJlgylVAEE8Y3EfVXsu7zjHYH7ygBRB+ulM5KYOgjdpV3j1yDQ+CB14rEgqCPg26o9nvf9AES9suBuOl80cvSkG84hQmIFJkb0MP07E8xsSjQ8cJmyCrgAnbe0RltPsLBchCxvQUPz5LC9Vj1xTbSI=,iv:sY08E9Y72rN13a7PEPc8wqLwLgy5GPF6YqS74XY9udE=,tag:V66hW+3+yK/Lq8WXvLTgQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWk01NmZMZi9jYVlBRmlm
            L1BjYUR2S2pqOWRKb2MyWHVaN0pIUUl2Q0Q4Cnc0NjNPbFAwZStuMDBZMjJuWW9i
            OC9mRHVNTnlOMGphRTNKakVsWDBZWGsKLS0tIFdNam1Lam9LUE8xSTVsTFZzc1ky
            elJORHh3S2hWY1hQOFBGck1JT3NDRlUKkAB8YCsYF3lkMYSCcnjiH0orz2iYNdZb
            HjVSs3CNvcO8c0/kBTn5IO/twkranE6sZBGKEYwNcqoKSqZwnXNZAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T08:38:43Z"
    mac: ENC[AES256_GCM,data:fzT4Mca5LrXJX/LLoF46dw/OJJIPE7q9INlXPIz7rB5+w65UvA7xLteptmSm2Alkc/zBk86qacuI2qoAMq4aAb/sOsdk+U61e9/PSdRX6fMSMfkjvPb1gwONArmjyIrNkKKqOcdrIYskXvm0fcQTyAa6I22okLLjzet/PvYMccE=,iv:jeAuTjBc3/e8iybD3t5V7KI5X4yvqwRep8KeK0/VNeE=,tag:ur7vW5GFd6A+rAWL1zX4eg==,type:str]
    version: 3.13.1
