apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:/m0XK8f0Av2UW9ye2VR9YOzqdeVRW4zKy2qrJX7XDrd/cyqwoQTCfz/1qSImSlHpHusxEzdPEB2iH5q39C/8St+nkHgcgH7CDzd0gdMDPz9JoiIEn+IXPBft+RhAQkjDMkhjh+bd5pm84wPGL217oXVAprNyTACHnZpAtPBPSwQ0AdQSE5AJcqXjgS4NlzxoOqoG3CWPL1J2r+Grqez59q4LiFMUiuOoSSXg3H+eDu+/dy9yr9Mg/v+EpPjCObqZhGqwQxRk3m9/hdbQ9QMauaugtu+NT7TQ28uvFcz/bn/NVncQRNg923G87qM=,iv:3k8388Dm/1jJSMV/wpV5G7PAsHkD2lhv2GVvWYoIY0E=,tag:Eb1hyBWyUJk129nXIVYY2A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-radarr
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBId3EyTU1QaTBVWEdTNVBB
            Y0hORFBkY3htSUl3NUFQTytsMHZqZWRYVTNVCkUrMXJIYjBETFhWdUpSSXVWODBx
            bnk4VXNEL0cybzN2SkFESXovbm5mQlUKLS0tIEw0YmFILzJac3JwMGZQZ3ZQdFJX
            WkhidHNIYjY3czArdTZlSG9Kd2F2NEUKp1LD7ccXB1q0V9DUbrZK2JNRWaCu9abT
            QC1/oRlo4azzj4uN/AttR67t4BH3akaSekKJPncsKouP15KL6erVBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T16:02:04Z"
    mac: ENC[AES256_GCM,data:P5vLrCjAD36x02m3e0gMbUZvzuGLP4FCt8oLZK38B/BQ5DHTN21UvKSVN6mTt4zVEB/2ERP6FGRyONFqhK61cXZCFdiNVs8OqK6SD26dkADeVJi2AUKblRUBDHB+xsjyK3t++r2EThRN/6MiI8m4fX1ed3GPnDNK4kpTT1lQCq4=,iv:mau/9QyWIVRpRgnmdi74HFoe11NXhwD/tYCeymPAhoY=,tag:AHQYX+r64zu6KBwOeyVAEg==,type:str]
    version: 3.13.1
