apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:kH1HjVAu7p831HRzu/VfPedW0vtYNCJF7vcjaBcM26sNHRhagAPZEQ/aISMM0lZqb4uo8iqosl/P00/pjFzoVPlys0e74zKO3RhrHGvDCw2kul4/Fn8v9VLT0HhU2KiwKWjPFO81gXiybRK1rD71JDiSazPK71amKoi6GfmTQlGrsJqHlWZ6YwyFKOIpGKmhYPqQ65eq2CNtxtiqEMhhW8MXEVFpkAjNONOqpDi4df8h1sKHFSOThtAVHLw4ZIVkjnz9m5uva8+Vq/T0f0Sq3diCYYngBcjygywxhHAXQXJvHqKkJZ80+c2cL6g=,iv:0cHkeZFqLftoqaCCRoJWJFuTtXyjq7wIOR45gOGRpvY=,tag:TZ2d6CAQTI9PoISwIqEwhA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-seerr
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOEk0NkZWd3VZT29sVEJB
            Rk9XbEh5c29RZ1pLRi9RbjdHSzVWUTdUZVhZCjVnaG56Vm9LMGEzczlWeWFKZ1Ju
            c3V0dm9ETjJra1Z6eS9meTByOU16VGMKLS0tIHpZMzAycWFUc0RtRTNwMS9yeFcv
            OGcwNWErMlg0eW1tQ0lFbUFIMllmbVUKbCoYKSs8Vqu60LCO8iYD0u7/HXYv8KVv
            fr47zfmiNlvQ4q22vONjZkqlHZ1/kQAW+7bzx3hGygEBwHpJog6FEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T16:10:29Z"
    mac: ENC[AES256_GCM,data:JmW+XEJLsBS1PIHiuCXqS11IsK1v96l1MLIWE88jv5+3p2BOYO2ikMdN3KelvGxUO4M/gpi7u9iBPU4ST/+9Xre16qAgZ/qR2S3q6hoeK+rlKZQcV1hPftwVmeJte1hRxIFRRwlC7MByJfVnImEVF3sVHoI8rehnb8RmV9oFavY=,iv:mLkNO/RFWBO0jtKqrcHuewgzChpsX7+SvMOoMU7NoTo=,tag:PhrsBffHqNmrRo0K2cCgdg==,type:str]
    version: 3.13.1
