apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:VFXxjbaAHS2pIh94ZZC6Uc+hwj9zyRPADnUnLizA/9yvcdZerOj/7umRRmQXl8JAcOsHdo1NnVeQElzyLdgTDOJdfnCDbzHClMWnEtJqhksgTW0ZElJ+l/3mEup+Ne1YYskOQE5yWGzK/9NUNy2UStf8X4JnvGKNd26gFujPBUId1v/r9zOIxw4ADpedkiHPZHs2YWhZZgIyLycyG2QtLeJSIV/bgM3ERXMTSp0rHSrubAnYxIupiSZGJrWSy15lGU71ZpTI2fh2/5QcUhEJk623rlO7wx0ZKIa/rsDkSsUCONXgnaiIarP2d3Q=,iv:ayiXt1I/5XI9oqwu/JvEgPW8kLDsdF7KId1qbIdI5O4=,tag:RRWMIv2gVq5+JgiyRaCzyw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-rdt-client
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZnQ2WjM4TGZ5WGxxZGcv
            Z082V0t0ZUh4eEprNi9ySWFwSDdDU29sd1FRClNkYjhpUmNRSC9LeFNMbkFJSWZn
            VmdEcHkvaXdva3lKWEZIQWhSRGlZcTQKLS0tIEx0YjVveEpicGl2VWhXOTVCMWl0
            bXNjL2JWMjcwWnJselNhWWgvbG5kWkkKmqXruvrRRByyggwwYD7FO/rcI7DsRlHv
            rngjpEt/hSjvPqINDlWHHhIggAvdeh4ys1c7APFXUJ5Yd4XkvIoEPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T15:16:11Z"
    mac: ENC[AES256_GCM,data:uG1a61qaydacwSh17B9BpwhbKBjzieTuSa7pdFsdwyFpxJbKC1IT1k+v0raPViexNIW10so+ludjcfyP4zMN0zzK29Z8Hw5XSQFNebrrDZ3TVNqjWFGwf8l8MzEUdbhou6f8dCaQJaw0gzZqSleoIOSV5yuuan0PkqE/Pj1ECIk=,iv:sHYCY1iwGYxsqe1nSBGj7vG2Cgnb81N0L0TwpwLr4D8=,tag:6P6a09MLmkn+u9uxESzXng==,type:str]
    version: 3.13.1
