apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ul4pptLcH6yfpH+0yjUdhv85cNAxLI4mHotKOyEZAy+ClsRd5ZRq7CehWxVMLrKxxmcmrxILW3UNIi3ew4SeJLxslmZ1zMOuieCKw0wMz9IrX4tX24HQ7DMG2HFteuL6B6o+3ff+3iDdIQvNaUBY/pjnfNFiw4T1oEZzBRKjCjrLqx9biXzQorxrFPPPddKRfCjrP6hGHSdQ3GZhI5C6O2qDjctXMKP822IR5NGJvM5RQSRjeQJ5QMWlb3qlNPTBGpP+RvzPRanWk4dbsPuJQUxKDaLIU7aSGUngl8cS97SPBHmxqE3/MlOwOB8=,iv:Dr7ZSjTeYDqM5ZP6XgLNhVFCk1+Xzrl1vTR2kLiywG0=,tag:9IZORgwAShlWHFQzq50hwA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXLzY3bHhveE1kb0thZVFE
            TGtBRnZqQUMxMEM0Z1ppZ1lvTzFweDlMeVRZCjF6WEtwTmRYWjVGSlJSQTZoa2c5
            NHljUUkzUFNkbWJXTXFyUzM1Z01jNkkKLS0tIEZMMHpsaGxMSzFPWFRUK2p1TXlR
            YXRtbjVoT1hSK0JVRGJjbTJGakMzbmMKaxRzTUltSGBh1/DQsla1lMpbLXR8GePi
            +05gRqwtNMJUbBy/beDCEgeuJ4A9pVPmmrTIJgygBMtRcrtb2CFqCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T16:49:57Z"
    mac: ENC[AES256_GCM,data:IJhrh8RN5bCUfmoOA2OQ1YALgRCQci4CDMg5DKvOTmIEG8wKtW9exK5iN0q+h5iUNoKkt2DmzugSqRQ3+hFmo3fo5VOCEJbVaFFDtoBOUb9cHLGoeqkQ3LN1tZKpVJirz85Z/os4ory+TJ0GUuGnMfFUbeqPNXp6x01xZ4ggvu8=,iv:Yg+hyzIB1Blmi2t7G3e0jjKcKzWNuPnG8OOfvxBkhEI=,tag:SKTjhXwFNk/kjJYWa5RMeQ==,type:str]
    version: 3.13.1
