apiVersion: v1
kind: Secret
metadata:
    name: comet-prowlarr
stringData:
    api_key: ENC[AES256_GCM,data:SI1VVbDkaZckq/RxdVQ6kS/kf/ardU5CTUBJw/G4kw4=,iv:x9pKWJ8kPDAwTRjpe1EFgMLSBpGuDVSKy1/D2lsLvBc=,tag:5Jd50Gd7AHQeK2w77SRFkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNDZmUk9QaGVkNnNDbGsx
            VTRnRXFBQ24xdG1VOWRrRmc1elo4YUl4Z25JCjkxZ0UrY2oyeG9ZQkVCcVB3NWRQ
            UXZtbkVDNzhYb3dTTlZldzdiaW52RjAKLS0tIHZ0b3NkRFNhZFUySFVzMzA4UHRo
            UDErZkFic2FIUml5cnNKVlpFN0xRMk0Km+44irYUyX5rGuW1g2llvPvJaPYoIGDr
            25BcUSvwrG8WyGFj2G79WpK5tHJCVYDmtFhD5ubABHKGLR1Z01dj2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T17:39:16Z"
    mac: ENC[AES256_GCM,data:FVLNxSl/e3+6D5j82L11njMkMiGLch6bHNrbDjqKKaTnD47Q6O/oh7kxm+G0WUJ00XV38+IFHlb6L8WsojmLECFu7jRBkUsQo0o78SnPyMZX9D0EZbelTEyKdGFLODfLmPF5nY+tENazJhM6znkQlKH0Yx5WLRc5zwDdtqt49DM=,iv:UC+kodbPQBPuxcrRd8S6GknX4006HI/65mAM72Ov+8U=,tag:QBYtJUEK1TBurk9u+U7kcw==,type:str]
    version: 3.13.1
