apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - urial-lab

      securityContext:
        fsGroup: 911

      initContainers:
        - name: init-dirs
          image: busybox:1.38.0
          command: ["sh", "-c", "mkdir -p /data/media/movies /data/torrents/radarr"]
          volumeMounts:
            - name: data
              mountPath: /data

      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.2.1.10461-ls305
          ports:
            - containerPort: 7878
              protocol: TCP

          env:
            - name: PUID
              value: "911"
            - name: PGID
              value: "911"
            - name: TZ
              value: "Asia/Kuala_Lumpur"

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: data
              mountPath: /data

      restartPolicy: Always

      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: media-pvc
