apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:VlTUP55QBppJs/nwPIj7MHkBWN+JDYyBuodikuTt31dutfjxhaXtZ5clXLTgl+fwlfEcHi561wRfQL9PspQX0LfV49Jo6MjdQdM30FeX2YrzdO5Nsc5y5ZYsfkYku2oFrg1v48h2VSFcscXd/I+kkf+5BXUp2LDrrfVsICwnrlw8B8lNjWkJVqh549ZXqiJY0y1OXM3KuKdvAs4yKt9xg/tm8bBoQaSCx6oSvKRhlB2idYYDXq7du61fgqL6FGTbHklZ3UmilSSvcl2uAxSq0+BBpp73sQygYP5k01QOZWqef3esKIPZ4MXPuHc=,iv:n23gfIVMTPPic25mXVv5s4JNPr2K2EbyqnD2M4UfIEs=,tag:+KhxLm336b5InS0d6NPH6g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-jellyfin
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWGlYOVFyZ1o4VVZHMTFw
            V1BDb3k5SUJvdU94cEVhajBKUW00cmxKeVVZClUxRmYrUTU4Y3RpMVhDUVNxVktY
            OEFpQUo3SVpLWFp2ZUptOXc4dXVVYzQKLS0tIHhlK1ZOdExCanY2MjlBQUozN0lI
            dGxoUytBMHpVcWJvNzFIcDdBb2JGT2sKywz1LYdJx2QtMJFyPRA1T6SDCtz9pXAe
            vdukz1BmweDWTX5zi+4tPF12BaLAKtZKRly8ePIhr5famwTuWUkChQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T01:32:20Z"
    mac: ENC[AES256_GCM,data:r7ejfq5WEeQZxcKvcdEvL6Jv+29hAB5vhhGRVKE6cV868qVpPuEelSnyQDevIl5b/sK2a8ITDESD2FAjOT+W232KPH+NFHP59DnQzz5eKqhYeDsaTJsT+uStY1QpKj4U5fVyqDeTGzkxKWi3jLbt8JccCpqqDbyogT/0cEPVbkk=,iv:SKAb1LDhIfmOF0PY3EXY47yKBFmFE2ea9O7vG0Dvlk0=,tag:4XsFBpZswgRZ7hfC95kTdQ==,type:str]
    version: 3.13.1
