apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:1jb9gCLNLD+WxVGSgKzSZWOj+CevhX49tnBdaQA4xyL+TsPcGPvf2LgnQFdu+JDTWDNoc02cjTI0KTQFlhH8hRAnxR2zYt1Bo6HUJpmWp5P3t5MTSvOzVUnUVyMT4CYwa4beYnTQGHvxuuqR2tb9b4DCqmUHdxiFrwH3XP1aqB40oHwFxt3e8Xpw6SK2Ko8rmdt0kdcUi3vRelJ0mNliHqMGMj4kYrlcrKYamPHvOZBA3oXAZ3Q1yTJyxYGcT+TuC9uwruRmoFwvxO/Rd1VwD3IyPxhMZxPqA2mLqHzZEzfEsojoSf41q6sl2f4=,iv:+p63cMdGM9mJB6xsN1huorNPu1CwU1CGkBdroi3p00Q=,tag:Cf9KRqFlDFIH2s02i/wsZA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-jellyfin
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcWxLVVB5VGRyVk5uTmRS
            SzhxNGRCRzUxbEdMRjJFYUk1aldxUUh3K2tNClgzaVg0RFNzU2hETWZVYTZZV295
            R0d2Z1o3dW9CUCt2Z0tpTUljcTUzakkKLS0tIFlpMWxqRWVHQ0wyQkp3NzBmaHJL
            cllmYzZsS1ZpekRzb0hkcCtFOWNwS28KXoikQ0vmuLCy8VVJJLQRaaftWzJKUk//
            UEKnDtQpSocEA5fliwiFKfNaPdxMuu3Kx1g35mxWx3bxDuQx2baZtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T14:54:29Z"
    mac: ENC[AES256_GCM,data:nuUvVMvpeBYBpQkIXhdEGC6n5YeYc9cxf7rsUNYEGIzJBjMiYI7XPGyZOYxK/e6e+PGmYF9xD4z3DXnkjcie/5GWIwO5Xk2uUmWEZDcC0R+oqEAtIB3TdRwJAH1N2qisEvsAkkXGg/xqyoqU3nw49WIYMLaYr+uAkD1ADlH/Ev0=,iv:M3tc3TWdAKsJp0ZgWyoT8krBgRKJpL/js9txQsLKhr8=,tag:P5dbnBVby783U+45kz5S5g==,type:str]
    version: 3.13.1
