apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db-production-cnpg-v1
spec:
  description: Postgres cluster for the immich application
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  instances: 1

  monitoring:
    enablePodMonitor: true

  inheritedMetadata:
    labels:
      app: immich-database
      policy-type: "database"

  storage:
    size: 5Gi

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-creds
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
        - CREATE EXTENSION IF NOT EXISTS "vector"

  resources:
    requests:
      memory: 600Mi
