apiVersion: v1
kind: Secret
metadata:
    name: r2-backup-creds
    namespace: immich
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:e3SyVYwMiPOjRXsyZGWYfTblNzrRpCe7G3CezbGLFWs=,iv:Dp/2QtBRSkafEYau2qahSABxaFFDFFBTxtDwJb3J5cU=,tag:r9BF62FRxDXMRSdUeBnJuA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:T6Q4emAF5Uh7ml6fUk5GBau1zPYxs1VFCFOuEGCo8A6adKmCsMU/Opr/w9e0B0weDPpU3tzYCLU37mAcz358JA==,iv:S2YrzHd3WzF70jdAt++yGoxC6Hzc5ytWGJxFp+lhp7c=,tag:AKw2BO6qYRjYe83Xj8gzKg==,type:str]
    REGION: ENC[AES256_GCM,data:eEOvNw==,iv:8yZsPSjrQUOEKhypkKz3k9gbjEDaNJn/qqHefZ1BnHs=,tag:z4w4n1FDdw4ESGPLJM/Qiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVUR3NDd4UHk4RElMSmNB
            K01kRXNFRCtxZG9YSytFRDZLZUorTHFKTXhBCnVFWVJ5SFJWbVhOR0RNZHJ4bW1D
            ZFVrcEtkVVFoMUszMld1bVRiR2Z0aG8KLS0tIDZLMit1d1B5OWMyTUZEaWdMZGhN
            RncwUEZza2JJS3pTM003bmlaMWU4MDgK112TObHuDuZnesNRf0Qaia9Z6znKIGrQ
            KVvXTozRz6JDTRVeIEIqrqrrxqlXflpQgqG2ZxEBplGvcvY/r58BKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T15:01:45Z"
    mac: ENC[AES256_GCM,data:gatExCyYS65wSoArLxBoNhCkTTXH7SNJUrWxYx80lfyzcXGd4UNwpH/a46Krdfr2O7ztm2RBRuDKQcfz8yXHAHwbPDX5KvYHOorgWX+fb0hnXIOQB/chXYWpv6QeX9zVaGzSU3QWdZOwFySLiMmIpfIDYeSEVYw2DAyWVB4ZsjY=,iv:1Ois/JKU9j/LfARbKZL0ayhJ69YgyxphAX2IBA66ahc=,tag:Zf8xl5ffPDtmKrQsifSfHQ==,type:str]
    version: 3.13.1
