apiVersion: v1
kind: Secret
metadata:
    name: immich-db-creds
stringData:
    username: ENC[AES256_GCM,data:RP6G4Akt,iv:/+TXRd1jENAt6oD3n03WQExMoaIq0NZ/A/auKhebVxM=,tag:yVdN6LmTBn9tqTG7xHtClA==,type:str]
    password: ENC[AES256_GCM,data:hqPbBTuIWnRj8h0v,iv:ItixDWxC7BCpcwh8t5yBG7eKEijoPam4dbbIWGflQAI=,tag:SGCef7d1xOVLoCYmBdt62g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZXFBUjVHUHVkSEcyajl2
            dXZqZDU2S3d6c0pBbkRCaVNUbUtPbDlMVWdVCmhqRU1Yby9iaS9vdGtmNlVhbjQ3
            SDVlQlFIYVNUSjBUbFA2cHpDd2lGRzgKLS0tIFhQa0JhWnpUOWFMZFUvazBNZmdF
            bjZ5dWFmaHNEVWFZdTVQdmU1TzBIUDgKcSZjVrjhz/TJFz/C4WQ2LdukAFHWHSNR
            iSMmqTDLMkEPkl1wIXo87G6TkdvwO6f/eWvMPLVP1Lnh74KnT4NkAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T05:44:57Z"
    mac: ENC[AES256_GCM,data:tsOGGnm5ftHSmmrKw4VGpyLQbo3FAC7nSVVs2mURa/Gwu+O3DItVx2Z3bv1HYKUW1xn7X171x3v+rEGu4d87d2uhja7hYKjMicXSKtLxcOKm4z1mwlMbwvASz9mpPiMQfG9+KF15Pj5JZv7i1pSiEbsGJXJJ2iJw1U6pgN9jehY=,iv:4SE1tmkft3nwdhXxOUXgyn+feb0gda6Gm7V/bxMsRo0=,tag:fcMmNF+pyjF7pstz6OZxyQ==,type:str]
    version: 3.13.1
