#     DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:tLYkklLAS9LAYNoiKLwwYA==,iv:vITc/EDHxm6eXvoHMZOOJX/vIfgSet1eXgfEP9jkz7A=,tag:2IHc/0aPZCXUuLMKveZB1g==,type:str]
#     DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:xAOQxvcRTekTnaZn,iv:EwiD48Xkftlv/G1orHNeWub5E663nK7G5V+cdQG7s1U=,tag:If38GzG/eevJ/OiTkTsDAg==,type:str]
#     DB_POSTGRESDB_USERNAME: ENC[AES256_GCM,data:AEm7b2BuvXQ9v8Iz8BJ61Q==,iv:c14frjfiuKrsPcGLqALl0qmh6mRyES2h31WpW2se8os=,tag:LdFi5P+mp/tfWaYX+L+dLQ==,type:str]
