apiVersion: v1
kind: Service
metadata:
  name: rdt-client
spec:
  selector:
    app: rdt-client
  ports:
    - name: webui
      port: 6500
      targetPort: 6500
      protocol: TCP
  type: ClusterIP
