apiVersion: batch/v1
kind: CronJob
metadata:
  name: spotdl-sync
  namespace: navidrome
spec:
  schedule: "0 */4 * * *" # every 4 hours
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: spotdl
              image: spotdl/spotify-downloader:v4.5.0
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  while IFS= read -r line; do
                    [ -z "$line" ] && continue
                    spotdl --output /music download "$line"
                  done < /config/playlist.txt

              volumeMounts:
                - name: music
                  mountPath: /music
                - name: config
                  mountPath: /config
          restartPolicy: OnFailure
          volumes:
            - name: music
              persistentVolumeClaim:
                claimName: navidrome-music-pvc
            - name: config
              configMap:
                name: spotdl-playlists
