apiVersion: batch/v1
kind: CronJob
metadata:
  name: spotdl-sync
  namespace: navidrome
spec:
  schedule: "0 */4 * * *" # every 4 hours
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: spotdl
              image: spotdl/spotify-downloader
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /music:ro
                  while read -r line; do
                  uv run --project /app spotdl \
                    --output music:ro \
                    download "$line"
                  done < /config/playlist.txt

              volumeMounts:
                - name: music
                  mountPath: /music:ro
                - name: config
                  mountPath: /config
          restartPolicy: OnFailure
          volumes:
            - name: music
              persistentVolumeClaim:
                claimName: navidrome-music-pvc
            - name: config
              configMap:
                name: spotdl-playlists
