apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-upload-pvc
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
