apiVersion: apps/v1
kind: Deployment
metadata:
  name: komga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komga
  template:
    metadata:
      labels:
        app: komga
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      containers:
        - name: komga
          image: gotson/komga:1.23.5
          ports:
            - containerPort: 25600
              protocal: TCP

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: komga-config
              mountPath: /config
            - name: komga-data
              mountPath: /data

      restartpolicy: Alyways

      volumes:
        - name: komga-config
          persistentVolumeClaim:
            claimName: komga-config
        - name: komga-data
          persistentVolumeClaim:
            claimName: komga-data
