apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:fiU2R4o=,iv:M2aypdBzIt+VUKAbt65tl/5ZkX1YPbyYadMkeVyDAk0=,tag:u8UtLeVPzEO47cpoRgh4OA==,type:str]
    admin-password: ENC[AES256_GCM,data:Z8Bi/KqumJ9hLXQKRvL9l/pVIQoGo+dPIOBtISlsWw==,iv:9USfFw3phLaMI7LaQSnSx27FYM3q1RBwd7PZGZsAr+0=,tag:yGRfbvgVVxwj7xSw2347Lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSkJmajVTRXhJZEM3aFRl
            eFhucVZ2VHRFc2c1cWZPT25BZ2xyY1BiSERZCjZUMTZPY1NJMDFSYiswTldsOTIw
            K25HMjVsZUR3U0NJNFZRM2JhK0JZU2cKLS0tIEFOQmtURUYxbmhteVN1U0JwZ0F4
            c3pOdndkbC9XV203d2NORndhbW1xTGMKRc0T3JNeSPMnKzC8ywhUldChMYI0RXQk
            roP3fgkJipoOXHKHHlSrcqcaf3gMPiTSKWnf15FzvsDCj79tzBefcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T13:48:57Z"
    mac: ENC[AES256_GCM,data:dn0MM4db5Q8PJ0+JcPNU1WmT4FF/sQhPmjFRS8groz0cwCIDEpV+NbmGpfPYMBUF6nTpl0hxnxSx2ibBMvO2jOE24G2ZLRUSdo3+zj0SriO/MdrRJWj0mh1t217jfISYx3NC2zM1SeUcJ25ELgQAN4ZK2LSrQpavK7m1kst29Bo=,iv:MHbL93+oHs1ll1U6XiHV5E55mUxjt4vG20oBAh51TIw=,tag:km6+nHKA+XmNyfJogAtBug==,type:str]
    version: 3.13.1
