apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Hc4IXBiq2K0=,iv:NR7LysMs/G0K2iG8FV85xtHX9sPzh0LxrsVVS5yXoBY=,tag:PxrjkpjTOtDFh2yL6/bRqQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:JxEpLNd1S3dU12Ki,iv:2WgFX2vY6lleVQccXSPLJDtF9vemDIITp3iU9lm4fyY=,tag:nQsOuJYbh2tZdAod666GTg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:k5KLAaPDmFh/Skk5x0CFwTw7MMTwsA==,iv:m+jk6AdmSlhAYJSDq++vHMUeSz2AoAAXsrgt2ZFP3Wo=,tag:dwsHIgzKV2dCfStowrsOtA==,type:str]
sops:
    age:
        - recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0emdoaGNhcHd4ejg1dmpZ
            S2NoeGJUa0gvdXZyang1VDBUcXE5c0VIWHdnCkl1S21veVhGemdXNXpMMTYyZDRx
            SS9HUGJZVWlTRktRTUsxTlFXWldwV3MKLS0tIHJpWEZLVkM4U1hKamM4MHJlVVBB
            R0lObUdWMUV4NzVCSVIvYXVHZjhYUFUKr5Q9x41ENWTfeTseaSo2P/iiNL1g3ctc
            aQw2yO0mU0RMnUavaHnrVMlRZwexhdLD1XvVXwfImBjPIo/jLxAz+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T16:49:05Z"
    mac: ENC[AES256_GCM,data:hB/VrrpCcFGYoh0/HDMYBAFR7nZ/c6MM3+zhdsnNHrNZYfn7mZIabLO53hsGPSAwXdYqS07fondNHVK82tcmkeSYxKiYmRlqlyXmJ3OvY/Eh31mqEIivxWvhPqkRaLAC+KYWcvgxLpaNR54uLeTm0c/nkMjBLUxzh3yMxHzF060=,iv:sPqtYS9NbiPqQabhqYq5mmuNf4AViygOlqpWPUYP3mY=,tag:229RJPQ96u0Gy+sxisGdCw==,type:str]
    encrypted_regex: (data|stringData)$
    version: 3.10.2
