apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: ">=0.9.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
  values:
    immich:
      persistence:
        library:
          existingClaim: immich-library

    controllers:
      main:
        containers:
          main:
            env:
              DB_HOSTNAME: immich-db-lb
              DB_DATABASE_NAME: immich
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-creds
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-creds
                    key: password

    valkey:
      enabled: true

    server:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - urial-lab

    machine-learning:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - urial-lab
