apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:KcPNDRotFBLe/PpMT1KPPEKke0Ioa3FH9zvqBZKCSwxl7kg7NqYCaO3QaxruGLGHq1tCse5E8KvM+YS86az+beGxnt3lo+MjlpLU+Hj1xK8BClja/kmp7hk+/HgLrQMEcgwpXmqyqGdWMTv/Tz9gt7gFwxcSksoM2GZpjX5bmncFRitPOQzZhQd5QgCvQvBqvnO4MLQaUVK0/+6A0gEkGvwXfL5b0rIXOABFv0wMcJi/xzVXlfj21HcS1Pt0BRv5qMk0Vm7gMYSdq5IW+8fKZr/quPPWu21sROJfQbKw8uj329HfSJqra9BhF4Y=,iv:6w10tJ8pnPMd7kd0deROkzI50idPmDLsWw0FyjIzP+I=,tag:75lC0VW05G6uvresZmeS6Q==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMkhFamRiSXFCc2lzb0hN
            b1V1bmpIcllTczhKL3JHdkJlNXVaNUROUDNvCkxVaGlrY2xOOGcyYU5TSTEwbytU
            eEdNMm9VSUtNSHdOY3lXSjI1ZnRvam8KLS0tIFc1S1ZqcnR4N01lenYvTi80bWpv
            L0Z4OTlTWnUyL1RrZEh6QmR2VnlIVUkKwsQKZPkjaNcKRPj33PAMGtK6m2uMqzy1
            xMZ9qUxFerH/Q4c9kiCGUO3PJvpd5TXA6BnXFDb4AXbfn5GI/ro5yQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1av8wp2lg5m6anyd94jg9x67st3prnkfnacrtl25ptlzjmc06gqsq0w85c3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T16:54:36Z"
    mac: ENC[AES256_GCM,data:RT9hsTZ1vRjhJ5giz/0C7BbpcRkcZbhE0byRtP9o5jmkNCgS8GjHBKeibpTQDGo/lB7t8BdpZzwXOgv01LYlC4Bl775B1YJ+REj46UY5rbLZzzT5hTeOX/dJ7PA7J8Na9ClVmu2IPwr/KanfI6OHF7CKzFtanb/t11ocAAdB+Xc=,iv:fchiJ08WHMVO0EW/ENVjBONVXFVcUjhRculqt6o2IFQ=,tag:xNQPPhW7l/7s9MO5hMOjkA==,type:str]
    version: 3.13.1
