apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33

      containers:
        - name: commafeed
          image: athou/commafeed:latest-postgresql
          ports:
            - containerPort: 8082
              protocal: TCP

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: commafeed-configmap
            - secretRef:
                name: commafeed-container-env
      restartpolicy: Alyways
