apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsGroup: 3000

      containers:
        - name: commafeed
          image: athou/commafeed:latest-h2
          # image: athou/commafeed:latest-postgresql
          ports:
            - containerPort: 8082
              protocal: TCP

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            #   # - configMapRef:
            #   #     name: commafeed-configmap
            #   - secretRef:
            #       name: commafeed-container-env
            - secretRef:
                name: test-secret

          volumeMounts:
            - name: commafeed-data
              mountPath: /commafeed/data

      restartpolicy: Alyways

      volumes:
        - name: commafeed-data
          persistentVolumeClaim:
            claimName: commafeed-data
